car_model:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  rear_right_wheel_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: right_rear_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_right_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_steer_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  rear_left_wheel_joint_position_controller:
    type: effort_controllers/JointVelocityController
    joint: left_rear_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_left_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_steer_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
